const ApiMessage = {
  NOT_FOUND: "Not Found",
  SUCCESS: "Success",
  DATA_SAVED: "Data Saved",
  IMAGE_REQUIRED: "image is required",
  ACCESS_DENIED: "Access Denied",
  ACCOUNT_NOT_VERIFIED: "Your Account is not Verified",
  ACCOUNT_DEACTIVATED: "Your Account is Deactivated",
  EMAIL_NOT_REGISTER: "Email is not registered with us",
  GROUP_NOT_REGISTER: "Group is not registered with us",
  USERNAME_NOT_FOUND: "Username not Found",
  INVALID_PASSWORD: "access denied. Try again!",
  INVALID_CURRENT_PASSWORD: "invalid current password",
  LOGIN_SUCCESS: "you have successfully logged in",
  USE_ADMIN_LOGIN: "Use Admin panel to login",
  ROLE_REQUIRED: "Role is required",
  EMAIL_EXISTS: "Email already exists",
  USERNAME_EXISTS: "Username already exists",
  NOT_MATCH: "New Password And Confirm Password not match",
  PASSWORD_VALIDATION: "Minimum eight characters, please",
  COMPARE_PASSWORD: "New Password can not be identical with Old Password",
  USER_INVALID: "User is not registered with us.",
  INCORRECT_OLD_PASSWORD: "Incorrect old password, please try again.",
  LEVEL_NOT_FOUND: "You are currently not in the level you have selected",
  ANSWER_SUBMITTED: "Answer submitted successfully",
  ATTEMPT_OVER: "You have reached maximum attempt",
  REGISTERED_USER: "You are not a registered user",
  REGISTERD_ADMIN: "You are not a registered Admin",
};

module.exports = { ApiMessage };
